Deploy circleci (#20)
* Empty commit for testing purposes

* circleci init

* test deploy

* test deploy nubeproduct

* test deploy nubeproduct 2

* fix config

* fix config

* added circleci config for dags/src

* test dags deployment onto s3

* test deploy nubeproduct 3

* fix error on parameters circleci

* fix error on s3 bucket sync test

* fix error on s3 bucket sync test 2

* fix error on s3 bucket sync test 2

* fix error on s3 bucket sync test 2

* fix error on s3 bucket sync test 2

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,7 +25,7 @@ parameters:
 
 # Custom commands aimed for the main workflows and jobs
 commands:
-  deploy-dp-nubeflow-dags:
+  deploy-dp-dags:
     parameters:
       dp-dags-location:
         description: The location of the root folder for data product notebooks
@@ -38,6 +38,19 @@ commands:
       - run:
           name: Deploy Data Product Dags and modules to Artifacts Bucket
           command: |
+            # Print the bucket name for debugging
+            echo "Using bucket: $NUBEPRODUCT_ARTIFACTS_BUCKET"
+            
+            aws s3 ls s3://bi-nbflw-artif-prd01/
+
+            aws s3 ls s3://dn-dbtdp-artif-prd01/
+
+            # Ensure the bucket variable is set
+            if [ -z "$NUBEPRODUCT_ARTIFACTS_BUCKET" ]; then
+              echo "Error: NUBEPRODUCT_ARTIFACTS_BUCKET environment variable is not set"
+              exit 1
+            fi
+
             aws s3 sync \
                 << parameters.dp-dags-location >> s3://$NUBEPRODUCT_ARTIFACTS_BUCKET/dags \
                 --cache-control "max-age=86400" 
@@ -54,6 +67,17 @@ commands:
       - run:
           name: Deploy Data Product Project to Artifacts Bucket
           command: |
+            # Print the bucket name for debugging
+            echo "Using bucket: $NUBEPRODUCT_ARTIFACTS_BUCKET"
+            
+            # Ensure the bucket variable is set
+            if [ -z "$NUBEPRODUCT_ARTIFACTS_BUCKET" ]; then
+              echo "Error: NUBEPRODUCT_ARTIFACTS_BUCKET environment variable is not set"
+              exit 1
+            fi
+
+            aws s3 sync \
+                << parameters.dp-dbt-project-location >> s3://$NUBEPRODUCT_ARTIFACTS_BUCKET/dags/dbt/nubeproduct \
             aws s3 sync \
                 << parameters.dp-dbt-project-location >> s3://$NUBEPRODUCT_ARTIFACTS_BUCKET/dag/dbt/nubeproduct \
                 --cache-control "max-age=86400" 
@@ -201,6 +225,11 @@ orbs:
           - image: cimg/python:3.9
         steps:
           - checkout
+          - run:
+              name: Handle Python version
+              command: |
+                # Remove the .python-version file completely
+                rm -f .python-version
           - run:
               name: Install yq
               command: pip install yq
